FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install wget vim gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /neurify
RUN wget https://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz 
RUN tar -xzf v0.2.20.tar.gz
WORKDIR /neurify/OpenBLAS-0.2.20

RUN make clean && make && make PREFIX=/neurify/OpenBLAS-0.2.20 install

ENV LD_LIBRARY_PATH /neurify/OpenBLAS-0.2.20/lib

COPY ./general /neurify/general

WORKDIR /neurify/general

RUN sed -i 's/opt/neurify/g' makefile
RUN sed -i 's/OpenBLAS/OpenBLAS-0.2.20/g' makefile
RUN sed -i 's/-ldl/-ldl -no-pie/g' makefile
RUN make clean && make
